### ISSUE TITLE
Attempted to import "punycode"

### ISSUE THREAD

**Issue by donavon** [charpeni/react-native-url-polyfill#140]
I'm running the `expo-cli` attached to an Android phone and am getting the following error after importing `react-native-url-polyfill@1.1.2`.

```sh
import "react-native-url-polyfill/auto";
```

> The package at "node_modules/whatwg-url-without-unicode/lib/url-state-machine.js" attempted to import the Node standard library module "punycode". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
Failed building JavaScript bundle.

Is this a known issue, and what can I do about it?

**Comment by donavon** [comment]
I've installed the package `punycode` and that seems to have solved the problem. If `punycode` is a requirement, should it not be listed in `dependencies`?

**Comment by charpeni** [comment]
Hey @donavon,

Thanks for reaching out!

Which version of Expo are you using? Do you mind sharing your `package.json`?

**Comment by donavon** [comment]
It's the latest version and my project is a small test app built using `expo init`

```sh
$ expo --version
3.18.6
```

The `package.json` file is as follows:

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^37.0.0",
    "punycode": "^2.1.1",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-url-polyfill": "^1.1.2",
    "react-native-web": "^0.11.7",
    "thwack": "^0.4.1-beta.2",
    "use-thwack": "0.1.0-alpha.2"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "^8.1.0"
  },
  "private": true
}
```

**Comment by charpeni** [comment]
Thanks for flagging this @donavon, I've been able to track this down.

`whatwg-url` needs `punycode` and we didn't catch this earlier because `punycode` is required by React Native's default dependencies and hoisted from `eslint` and `jest`.

I'll add `punycode` as a loose dependency of `whatwg-url-without-unicode`, then update this library.

**Comment by charpeni** [comment]
Fixed by https://github.com/charpeni/react-native-url-polyfill/pull/200.
