### ISSUE TITLE
Error: Cannot create URL for blob

### ISSUE THREAD

**Issue by acostalima** [charpeni/react-native-url-polyfill#223]
The issue apparently lies in [`NativeModules`](https://github.com/charpeni/react-native-url-polyfill/blob/c32cbdc97fb6569edd6d941c3600196debeb0ad5/js/URL.js#L5). The import is `undefined` and, thus, `BLOB_URL_PREFIX` remains `null`. This [patch](https://github.com/acostalima/react-native-polyfill-globals/blob/master/patches/react-native-url-polyfill%2B1.2.0.patch) fixes the problem. 

Has anyone else experienced this as well? It's happening on RN v0.63.2 on my end.
@charpeni, let know if you want me to open a PR to address this.

Related: https://github.com/ipfs/js-ipfs/issues/2813

**Comment by charpeni** [comment]
Thanks for sending this!

Hmm, do you have a repro case? 🤔 

We should make sure to cover this with tests.

**Comment by acostalima** [comment]
> Hmm, do you have a repro case? 🤔

More or less 😅 
I'll prepare one and share with you shortly.

**Comment by acostalima** [comment]
@charpeni you can find a repro at https://github.com/ipfs-shipyard/react-native-ipfs-demo. Check out branch `repro/react-native-url-polyfill-#223`.
Once the app starts up, press on the "ipfs.add()" button and then on the "add string" button. The error will be thrown at that point. You can trace the root cause to node_modules/react-native/Libraries/Network/FormData.js, line 109.

**Comment by acostalima** [comment]
Ping @charpeni. Did you have a look at this in the meantime?

**Comment by charpeni** [comment]
@acostalima Sorry for the delay here! I'm struggling to find the time to work on this, but I'm definitely planning on looking at this as well as updating the whole package. To be honest, I think your patch seems like a good candidate, I just need to find the time to work on this.

**Comment by acostalima** [comment]
@charpeni no worries! Please take your time.

**Comment by kennym** [comment]
I can reproduce this exact same issue on RN 0.63.3.

**Comment by kennym** [comment]
@charpeni I've submitted a possible fix
