### ISSUE TITLE
Make react-native peerDependency optional

### ISSUE THREAD

**Issue by trivikr** [charpeni/react-native-url-polyfill#269]
### Is your feature request related to a problem? Please describe.
When a project depends on `react-native-url-polyfill` and uses npm v7, the `react-native` peerDependency is installed by default. This happens as [npm v7 automatically installs peer dependencies](https://github.com/npm/rfcs/blob/latest/implemented/0025-install-peer-deps.md).

The npm v7 was made generally available on [February 2, 2021](https://github.blog/2021-02-02-npm-7-is-now-generally-available/), and is shipped with latest versions of Node.js

This is a problem, as some packages which depend on `react-native-url-polyfill` may support all JavaScript platforms in a single package. Even if the consumers of those packages do not need support for react-native, the react-native dependency will be installed by default in npm v7.

An example is AWS SDK for JavaScript (v3) which supports Node.js, browser and react-native platforms in a single package.

### Describe the solution you'd like
Use `peerDependenciesMeta` configuration to set react-native dependency as optional in package.json as follows:
```
{
  // ...
  "peerDependencies": {
    "react-native": "*"
  },
  "peerDependenciesMeta": {
    "react-native": {
      "optional": true
    }
  },
  // ...
}
```

The peerDependenciesMeta is supported in:
* npm https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta
* yarn https://classic.yarnpkg.com/en/docs/package-json/#toc-peerdependencies
* yarn v2 https://yarnpkg.com/configuration/manifest#peerDependenciesMeta
* pnpm https://pnpm.js.org/package_json/#peerdependenciesmeta

### Describe alternatives you've considered
Setting `react-native-url-polyfill` as optional in projects which consume it.
Example in aws-sdk-js-v3 with another polyfill `react-native-get-random-values` https://github.com/aws/aws-sdk-js-v3/pull/2108

### Additional context
* The AWS SDK for JavaScript (v3) is exploring using `react-native-url-polyfill` in https://github.com/aws/aws-sdk-js-v3/issues/2138
* This issue occurs with another polyfill `react-native-get-random-values` when AWS SDK for JavaScript (v3) is installed using npm v7 https://github.com/aws/aws-sdk-js-v3/issues/1536. The request on `react-native-get-random-values` repo https://github.com/LinusU/react-native-get-random-values/issues/27

**Comment by trivikr** [comment]
The RFC on yarn package manager which had introduced `peerDependenciesMeta` https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md

**Comment by charpeni** [comment]
Oh, that’s really interesting! Thanks for your detailed issue, I wasn’t aware of that feature at all.

I like the solution you described.

**Comment by trivikr** [comment]
Closing this request, as `react-native` is a required peer dependency for `react-native-url-polyfill`

The platform independent consumers (like `aws-sdk-js-v3`) which require `react-native-url-polyfill` for React Native support should make their peerDependency on `react-native-url-polyfill` optional instead. The consumers should also call out in their documentation that react-antive polyfills are required to be added by their consumers when using react-native environments.
