### ISSUE TITLE
Error: Cannot create URL for blob

### ISSUE THREAD

**Issue by s-kuniyoshi** [charpeni/react-native-url-polyfill#284]
Hi!
When I use URl.createObjectUrl at RN for web, raised title error.
Maybe this issue similer by #223.
Are anyone bumped this error?

I know that this library is not supported RN for web.
However, it would be wonderful if this problem could be solved with a little bit trick.

**Comment by charpeni** [comment]
That's a good point, `NativeModules` aren't available with React Native Web.

I would say you probably don't need this polyfill on web since `URL` and `URLSearchParams` are already there, right?

**Comment by gretchelin** [comment]
I'm also facing the same issue. I get `[Error: Cannot create URL for blob!]` error when trying to run `URL.createObjectURL(blob);`.  I'm testing in Android 10 device.

My `package.json`:
```
"react-native-url-polyfill": "^1.3.0",
"react": "17.0.1",
"react-native": "0.64.2",
```

**Comment by charpeni** [comment]
Closing this issue in favor of #366.

@gretchelin Have you configured your Android app schema to accept blob? You can have a look at this pull request for an example: https://github.com/charpeni/react-native-url-polyfill/commit/5985d7efc07b496b829883540d09c6f0be384387.
