### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by irfaan** [charpeni/react-native-url-polyfill#330]
Receiving the following after installing using option 1 (index.js):
```
[TypeError: undefined is not an object (evaluating 'this.localStorage.getItem')]
 LOG  Error getting session from URL.
```

Do I have it in the wrong place?

**Comment by charpeni** [comment]
We don’t not have any references to `localStorage`. Are you sure this is coming from this package?

**Comment by charpeni** [comment]
Do you use something like GoTrue by any chances?

**Comment by irfaan** [comment]
Ah! Yes, you're right - the only other include is `supabase` (supabase.io) for react. And the error triggers when this line is present:

`const supabase = createClient(endpoint, key);`

I included `react-native-url-polyfill` on the advice of this comment: https://github.com/facebook/react-native/issues/23922#issuecomment-648096619 -- which is supposed to allow the use of Supabase.

Perhaps I should also ask in that repo, but just in case - do you have any ideas?

Thanks for taking a look!
Irfaan

**Comment by charpeni** [comment]
Are you having this line: `import 'react-native-url-polyfill/auto';` at the top of `index.js`? It has to be the first import.

Do you mind sharing what your `index.js` looks like?

**Comment by irfaan** [comment]
Yes - error still appears when included at the top of `index.js`

However, **you were right above!** -- supabase has a dependancy on `GoTrue`! Do you know how to resolve?

**Comment by irfaan** [comment]
Looks like it's a resolved issue: https://github.com/supabase/gotrue-js/issues/11#issuecomment-734742485 (version 1.7.3)

However, the fix might not be included in the release version of supabase-js ("@supabase/gotrue-js": "^1.16.6")

I'll take this concern over to the supabase side. Really appreciate your help @charpeni!

**Comment by irfaan** [comment]
Okay - resolved! See https://github.com/supabase/gotrue-js/issues/11#issuecomment-873203394 for solution.

Thanks again @charpeni
