### ISSUE TITLE
Error using Jest.

### ISSUE THREAD

**Issue by aramiku** [charpeni/react-native-url-polyfill#331]
We are experiencing errors with polyfills using the Jest tool, is displayed the messages : 
	
	type error errorHandler , SyntaxError: Unexpected identifier

	at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
	at Object.<anonymous> (node_modules/react-native/jest/setup.js:439:6) 

in the file error-guard.js

**Comment by charpeni** [comment]
I'll need a bit more information to help you. This library is currently using Jest without any issues. Do you have a repro somewhere?

**Comment by charpeni** [comment]
Closing this as the stack trace doesn’t refer to this library, please reopen an issue with a repro case or more information if it’s happening again.
