### ISSUE TITLE
HTML entities

### ISSUE THREAD

**Issue by drpiou** [charpeni/react-native-url-polyfill#365]
Hi!

I have this link as example, with `&amp;`:
`const link = 'https://my.domain/pathname?action=theAction&amp;id=theId&amp;username=theUsername';`

When I use `const url = new URL(link);`, I have the following:
`const action = url.searchParams.get('action');` gives me `theAction`
`const id = url.searchParams.get('id');` gives me `null`
`const username = url.searchParams.get('username');` gives me `null`

If I debug `url` with `console.log({ url })`, I have the following:
```
url: URL
hash: (...)
host: (...)
hostname: (...)
href: (...)
origin: (...)
password: (...)
pathname: (...)
port: (...)
protocol: (...)
search: (...)
searchParams: (...)
username: (...)
Symbol(SameObject caches):
searchParams: URLSearchParams
Symbol(impl): URLSearchParamsImpl
Symbol(wrapper): URLSearchParams {Symbol(impl): URLSearchParamsImpl}
_list: Array(3)
0: (2) ["action", "delegation"]
1: (2) ["amp;id", "abc123"]
2: (2) ["amp;username", "qij2jg1lef5lgndnal9c"]
length: 3
__proto__: Array(0)
```

In here, the error is quite obvious.

The solution for me now will be to create a helper function which passes the link into `decode()` first:
```
import { decode } from 'html-entities';
import { URL } from 'react-native-url-polyfill';

export function parseURL(url: string): URL {
  return new URL(decode(url));
}
```

But, shouldn't this be done automatically?

**Comment by charpeni** [comment]
If you execute the following in your browser:

```javascript
const link = 'https://my.domain/pathname?action=theAction&amp;id=theId&amp;username=theUsername';
const url = new URL(link);

const action = url.searchParams.get('action');      // theAction
const id = url.searchParams.get('id');              // null
const username = url.searchParams.get('username');  // null

```

The outcome will be the same as with `react-native-url-polyfill`, so I would say that this is within spec.

I don't think you should have `&amp;` in your URL, this should be primarily used to encode hrefs in HTML, but the URL shouldn't contain HTML entities, if something needs to be encoded, it should be with % (e.g. `%20`).

Let me know if you have any other concerns, I'll close this.

**Comment by drpiou** [comment]
I don’t think either I should have these « &amp; », but they are generated with « & » in a backend, and sent by email with « &amp; ». So I guess it is more specific to my context then. In any case, this closed ticket can still act as a reference for someone else that may ends up with the same needs :)

Thanks!
