### ISSUE TITLE
Support for React Native Web

### ISSUE THREAD

**Issue by charpeni** [charpeni/react-native-url-polyfill#366]
Currently, this library isn't working well with [react-native-web](https://github.com/necolas/react-native-web) because we depend on `polyfillGlobals` from React Native:

https://github.com/charpeni/react-native-url-polyfill/blob/857044666d563b0558b2fd6e23d5736e620108e3/index.js#L3

We could easily bypass this with a `Platform.OS` check and fallback on applying polyfills directly on `globalThis` for the web platform. But should we?

What should be the behavior when you use the auto-import or `setupURLPolyfill` with `react-native-web`?

- No op
- Fallback to `globalThis` instead of using `polyfillGlobals`

**Comment by pradelkai** [comment]
Any updates on this?

**Comment by ricohumme** [comment]
I found that this polyfill is breaking stuff when I try to create an url for a blob on web. When I removed the polyfill it all started working again. 
However, I do need this polyfill for my native mobile build. 
Importing this in my AppEntry dependent on the platform unfortunately is a no-go.
So I wonder if this can be done with babel or webpack or something.
Thoughts?

**Comment by Andrew0314** [comment]
@ricohumme  I am having the same issue, have you figured anything out for this yet?

**Comment by tlmader** [comment]
I just used a platform check to work around this. It would be better developer experience if this was automatically handled!

**Comment by charpeni** [comment]
Hello everyone! 👋 

I removed the usage of `polyfillGlobal` a while ago to make it compatible with React Native Web: https://github.com/charpeni/react-native-url-polyfill/pull/373. Unfortunately, it was never released. Using the current state of `main` should be enough to unblock you, otherwise, I'm currently working on the project and will be releasing a V2 soon with a lot of improvements, including what you all suggested.

Thanks and sorry for the delay!
