### ISSUE TITLE
Parsing search params

### ISSUE THREAD

**Issue by ap1969** [charpeni/react-native-url-polyfill#441]
Hi,
First, thanks for putting this out there.

That said, I've got an issue that I think must be me, because it's such an obvious one:

```
  const myURL = new URL('https://example.org/abc?foo=bar');
  console.log("Search", myURL.search);
  console.log("Params ", myURL.searchParams);
```

results in the following output:

```
Search ?foo=bar
Params  {}
```

Again - that's such an obvious miss, that it must be me, but I can't figure out why!

**Comment by charpeni** [comment]
My pleasure, thanks for reaching out!

[`URL.searchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams) returns a [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) object, from there you can iterate over params with [`forEach()`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/forEach), [`entries()`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/entries), [`keys()`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/keys), or [`values()`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/values).

> **Note**: `URL.searchParams` returns a `URLSearchParams`, so the empty object you're seeing in the output is the `URLSearchParams` not the dictionary of params.

In your case, it seems like you would like to display params as a string, so you could use `searchParams.toString()` or as an object with `Object.fromEntries(searchParams.entries())`.

Or, if you want a specific key: `searchParams.get('foo')`.

Let me know if something isn't working as expected, I tested this in Chrome directly.

**Comment by charpeni** [comment]
Closing this for now, please let me know if the polyfill isn't working as expected.
