### ISSUE TITLE
Why are new versions not published?

### ISSUE THREAD

**Issue by SidhNor** [charpeni/react-native-url-polyfill#457]
HI, 
I've noticed there were a lot of fixes and updates but there was no new version published for quite some time.
Was the package renamed on npm? Or is there a reason it is not published?

Thank you

**Comment by charpeni** [comment]
Hey @SidhNor,

I'm still working my way through active issues and tasks to complete to be ready to release a V2. I was able to allocate more time recently, so expect to see a new release published in the next few days or weeks at max.

**Comment by charpeni** [comment]
There's now a new version published as `2.0.0`.
