### ISSUE TITLE
Crashes Reactotron

### ISSUE THREAD

**Issue by orisa** [charpeni/react-native-url-polyfill#473]
It crashes the Reactotron app whenever I want to view network requests. It was imported using import 'react-native-url-polyfill/auto' into the index.js file

**Comment by charpeni** [comment]
Were you able to capture a stack trace or an error?

**Comment by orisa** [comment]
It has been fixed. Reactotron has issues logging null

**Comment by charpeni** [comment]
Glad to hear that.

Feel free to open another issue if something comes back.
