### ISSUE TITLE
Incompatible with HermesJS?

### ISSUE THREAD

**Issue by lb90** [charpeni/react-native-url-polyfill#77]
Hi! I am using react-native-url-polyfill (with RN 0.61.5). After enabling Hermes I get:

```
info Copying 81 asset files
info Done copying assets
/mnt/store/MyApp/android/app/build/generated/assets/react/release/index.android.bundle:889:533: error: ')' expected at end of function call

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/mnt/store/MyApp/node_modules/react-native/react.gradle' line: 151

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command '../../node_modules/hermes-engine/linux64-bin/hermes'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 23s
139 actionable tasks: 139 executed
```

If I uninstall react-native-url-polyfill I can succesfully build with HermesJS enabled.

Thank you!

**Comment by lb90** [comment]
Additional info: https://github.com/facebook/react-native/issues/26645

**Comment by charpeni** [comment]
Thanks for flagging this!

`react-native-url-polyfill` should be compatible with Hermes, but it seems like something in it is incompatible with Hermes. I would say this is an issue with Hermes, but we can try to figure out what's causing this.

**Comment by lb90** [comment]
If needed, here's a very simple test case: https://github.com/lb90/TestApp

```
cd android
./gradlew assembleRelease
```

**Comment by lb90** [comment]
Here's the minified JS causing the syntax error: 
[minified.js.txt](https://github.com/charpeni/react-native-url-polyfill/files/4288146/minified.js.txt)

**Comment by charpeni** [comment]
Thanks for sharing your repo, I found the bug with Hermes. I'll share that with the Hermes team, then I'll try to patch `whatwg-url`, and release it.

**Comment by lb90** [comment]
That's so great!! Thanks!

**Comment by charpeni** [comment]
Caused by: https://github.com/facebook/hermes/issues/193.

**Comment by charpeni** [comment]
@lb90 `react-native-url-polyfill@1.1.2-rc.0` has been published to npm, let me know if it's working for you.

**Comment by lb90** [comment]
Hi, I've just tested and it's working!
